[book]
authors = ["buwu-DWJ"]
language = "chs"
multilingual = false
src = "src"
title = "dwj_mdbook"

[output.katex]

[output.html]
default-theme = "rust"
preferred-light-theme = "rust"
fold.enable = true

[preprocessor.katex]
renderers = ["html"]
