[book]
authors = ["buwu-DWJ"]
language = "chs"
multilingual = false
src = "src"
title = "∵布武 ∴不舞"

[output.katex]

[output.html]
default-theme = "light"
fold.enable = true
playground.editable = true
# playground.line-numbers = true
additional-css = ["theme/style3.css"]
additional-js = ["assets/custom.js", "assets/bigPicture.js"]

[preprocessor.katex]
renderers = ["html"]


# [preprocessor.theme]
# coal-inline-code-color = "#ffb454"
# light-inline-code-color = "#F42C4C"
# navy-inline-code-color = "#ffb454"
# rust-inline-code-color = "#F42C4C"
# light-links = "#1f1fff"
# rust-links = "#1f1fff"
